[sphinx.conf]
exclude_patterns =".venv,"
html_theme = "'sphinx_rtd_theme'"
[sphinx.paths]
parent = "docs/sphinx/"
source = "source/" # leave blank ("") if no source directory for sphinx
[file_templates]
# Set var to none or false to prevent file creation
run_livereload = """
from livereload import Server, shell

if __name__ == '__main__':
    server = Server()
    server.watch('*.rst', shell('make html'), delay=1)
    server.watch('*.md', shell('make html'), delay=1)
    server.watch('*.py', shell('make html'), delay=1)
    server.watch('_static/*', shell('make html'), delay=1)
    server.watch('_templates/*', shell('make html'), delay=1)
    server.serve(root='_build/html')
"""
[file_templates.rtd_config]
version = ""
[file_templates.rtd_config.build]
os = "ubuntu-22.04"
[file_templates.rtd_config.build.tools]
python = ""
[file_templates.rtd_config.sphinx]
configuration = ""

[pyproject.build]
requires = ["setuptools", "twine"]
build-backend = "setuptools.build_meta"

[pyproject.optional_dependencies]
docs = ["sphinx >= 6.2.1",
        "livereload >= 2.6.3",
        "myst-parser >= 1.0.0",
        ]

[tasks.init_file]


